### PR TITLE
Support GraphQL SDL via stdin

### PR DESCRIPTION
**Pull request by NathanRSmith**
Adjusted cli.js to handle the stdin case the same as a url fetch or local file. This allows the `--graphql` flag to parse the input as graphql sdl if present. Addresses #22 & #21.

### CODE REVIEW

**Comment by sheerun** [comment]
I think better approach would be to use istty option:

```es6
if (!process.stdin.isTTY) {
  console.log('Has stdin!')
} else {
  console.log('No stdin!')
}
```

**Comment by NathanRSmith** [comment]
Updated to use `process.stdin.isTTY` as suggested

**Comment by sheerun** [comment]
Looks fine to me 👍

**Comment by NathanRSmith** [comment]
Would you mind merging/releasing when you get a chance? Been a long time since I've done it for this.

**Comment by sheerun** [comment]
No problem, but the build is failing for old node versions. If you decide to break compatibility then please remove them from .travis.ci and add recent versions of node :) Also I'll need to release major semver version because of this.

**Comment by NathanRSmith** [comment]
I think the failure comes from a dependency, and iirc you marked package.json as node 6+ (https://github.com/sheerun/graphqlviz/commit/0323dbc46244ea08a94f8f241e4a0e761fd66086). I'll try updating `.travis.yml`

**Comment by sheerun** [comment]
You're right. Please just update travis.yml

**Comment by sheerun** [comment]
@NathanRSmith Sorry for the delay. I've merged this and replaced graphql flag with auto-detecting if input is graphql schema or JSON. btw. you have write access on npm so you can publish even if I'm not available :)

**Pull request merged**
