### PR TITLE
Bolded titles, added deprecation messages and made connection connect correctly.

### PR DESCRIPTION
**Pull request by miketamis**
starwars

### CODE REVIEW

**Comment by sheerun** [comment]
Hey,

Could you fix the tests as well?

**Comment by sheerun** [comment]
ping

**Comment by Glavin001** [comment]
+1 This would be great!

Awesome project. Let me know if there's something I can help with. Thanks!

**Comment by sheerun** [comment]
Hey @Glavin001, I'm glad you'd like to help.

I've added you to collaborators, feel free to fix the tests and merge this PR :)

**Comment by Glavin001** [comment]
Awesome! Thanks

**Comment by Glavin001** [comment]
## Before

output

## After

output

**Comment by Glavin001** [comment]
The tests are now passing. I will merge this into master and @sheerun could you publish when you can? Thanks!

**Comment by sheerun** [comment]
@Glavin001 I've publsished the package, thanks! Just please use squash-merge in the future.

**Comment by sheerun** [comment]
And of course thank you @miketamis

**Comment by Glavin001** [comment]
> Just please use squash-merge in the future.

Sorry about that! I'll keep that in mind. Thank you!

**Pull request merged**
