### PR TITLE
Fixes for #10 and #12

### PR DESCRIPTION
**Pull request by ajs139**
Various fixes:
* Add support for "GraphQL Schema Language" files
* Add support for UNION, INTERFACE, INPUT_OBJECT and ENUM types
* Added support to individually group the types
* Added support for arrays in arguments
* Added configuration for color and presentation (see README.md)
* Add tests for newly supported types

Examples:

Showing Input, Enum, Union and Interface Types (default config):
image

Showing changes to colors and style (updated config):
image

### CODE REVIEW

**Comment by ajs139** [comment]
Other ideas to improve:
* Ability to set a different root than Query, to 'zoom in' on a section
* Ability to optionally print `(...)` instead of actual arguments
* Ability to extract fields that link to other entities from the table, and instead have labelled edges
* Option to only link node -> node, instead of field -> node (allows dot to place anchors more freely)

**Comment by ajs139** [comment]
I took the liberty of merging in #11. Also, made the feature where the edges point to the type's headers optional to keep compatibility.

image

**Comment by rwe** [comment]
This looks awesome! @sheerun any chance you'll be able to take a look at this?

**Comment by sheerun** [comment]
@erydo Thanks for reminding

**Comment by sheerun** [comment]
@ajs139 Please add yourself as a contributor to the README :) I've improved your changes and releasing it right now

**Comment by NathanRSmith** [comment]
Nice pull request! Thanks for your contribution!

**Comment by sheerun** [comment]
@NathanRSmith Maybe you could update web version to accept theme.json and create some gallery of themes or something :)

**Comment by NathanRSmith** [comment]
Good idea. I'll try to get to that soon.

**Pull request merged**
